version: "3.8"

services:         
  iniciandoapi:
    image: iniciandoapi:0.1
    build:
      context: ./iniciandoapi
    container_name: iniciandoapi
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - iniciandoapi-network

networks:
  iniciandoapi-network:
    driver: bridge

# docker compose up -d
